apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tracewarden-tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        enabled: false
